config/routes.rb
Rails.application.routes.draw do
	get 'sponsor_restrictions/edit'
	get 'sponsor_restrictions/new'
	root 'home#index'

	get '/auth/google_oauth2', as: 'google_login'
	get '/auth/google_oauth2/callback', to: 'sessions#google_auth'
	get '/logout', to: 'sessions#destroy'

	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
	get "profregistration", to: "profregistration#index"
	post "profregistration", to: "profregistration#create"

	get "addProjects", to: "projects#new"
	post "addProjects", to: "projects#create"

	get "/profLanding", to: "prof_landing#index"

	get "studentform", to:"studentform#index"
	post "studentform", to: "studentform#create"

	get "adminlanding", to: "adminlanding#index"

	get "manageprof", to: "manageprof#index"
	post '/manageprof/save_change', to: 'manageprof#save_change', as: 'save_change'
	post '/manageprof/add_professor', to: 'manageprof#add_professor', as: 'add_professor'

  get "configuration", to: "adminlanding#configuration"
  post "update_configuration", to: "adminlanding#update_configuration"
  
	get "open_close_student_form", to: "adminlanding#open_close_student_form"
	post "open_close_student_form", to: "adminlanding#update_open_close_student_form"

	get "managestudents", to: "managestudents#index"
	get "/managestudents/filter_students", to: "managestudents#filter_students", as: "filter_students"
	post '/managestudents/delete_students', to: 'managestudents#delete_students', as: 'delete_students'

	# Defines the root path route ("/")
	# root "articles#index"
	get '/devtest', to: 'dev_test#index'
	post '/devtest/upload_resume', to: 'dev_test#upload_resume'

	resources :sections, only: [:new, :create]

	get 'changeweights', to: 'changeweights#index'
	post 'changeweights/save_weights', to: 'changeweights#save_weights', as: 'save_weights'
	# get 'dev_test/classify', to: 'dev_test#classify'
	resources :projects do
		member do
			get "projects", to:"projects#index"
			delete "projects/:id", to:"projects#destroy"
		end
		resources :sponsor_restrictions
		resources :sponsor_preferences
	end


  resources :projects do
    member do
      get "projects", to:"projects#index"
      delete "projects/:id", to:"projects#destroy"
    end
  end

  get 'prof_projects_ranking', to: 'professor_preferences#index'
  post 'prof_projects_ranking', to: 'professor_preferences#save_rankings'

  post 'dump_database', to: 'database_dump#dump_database'

  get 'view_results', to: 'results#index', as: 'results'
  get 'results_export/:semester/:project.csv', to: 'results#export', as: 'results_export'

  get "manageCourses", to: "manage_courses#index"
  post "manageCourses/edit_courses", to: "manage_courses#edit_courses", as: "edit_courses"
	post "manageCourses/add_course", to: "manage_courses#add_course", as: "add_course"

	get "viewProfProjectPreferences", to: "view_prof_project_preferences#index"
	post '/update_professor_preferences', to: 'view_prof_project_preferences#update_professor_preferences', as: 'update_professor_preferences'
	resources :view_prof_project_preferences do
		post 'assign_professor', on: :collection
	end

end

app/controllers/managestudents_controller.rb
class ManagestudentsController < ApplicationController
    before_action :authorize_admin, unless: -> { Rails.env.development? || Rails.env.test? }
    def index
      @students = User.includes(:student).where.not(students: { student_id: nil })
      @courses = Course.all
      @ethnicity_names_by_student = {}
      @cid = nil
  
      @students.each do |user|
        ethnicity_names = user.student.ethnicity_values.pluck(:ethnicity_name)
        @ethnicity_names_by_student[user.user_id] = ethnicity_names
      end
    end

    def delete_students
      emails = params[:delete_students_emails]
      @students = User.includes(:student).where.not(students: { student_id: nil })
      @courses = Course.all
      @ethnicity_names_by_student = {}
  
      @students.each do |user|
        ethnicity_names = user.student.ethnicity_values.pluck(:ethnicity_name)
        @ethnicity_names_by_student[user.user_id] = ethnicity_names
      end

      if emails.nil?
        flash[:error] = "No Students Selected."
        
        render :index
        return
      end
    
      if emails.present?
        emails.each do |email|
          student = User.find_by(email: email)
    
          if student
            student.destroy
          end
        end
      end

      flash[:success] = "Students Deleted Sucessfully"
      @students = User.includes(:student).where.not(students: { student_id: nil })
      @courses = Course.all
      render :index
  end

  def filter_students
    course_id = params[:course_id]
  
    if course_id.present?
      @students = User.includes(student: :course).where(courses: { course_id: course_id})
    else
      @students = User.includes(:student).where.not(students: { student_id: nil })
    end

    @ethnicity_names_by_student = {}
  
    @students.each do |user|
      ethnicity_names = user.student.ethnicity_values.pluck(:ethnicity_name)
      @ethnicity_names_by_student[user.user_id] = ethnicity_names
    end
  
    @courses = Course.all # Fetch all courses for populating the dropdown
    @cid = course_id
    flash[:success] = "Filtered Successfully"
    render :index
  end
end

app/views/managestudents/index.html.erb
<head>
  <title>Admin Landing Page</title>
</head>
<body>
  <%= render 'shared/generic_page_header' %>
  <%= render 'shared/notification' %>
  <div class="container">
    <div class="row">
      <div class="col">
        <div class="card">
          <div class="card-header custom-card-header">
            <div class="row">
              <div class="col">
                Filter by Course
              </div>
            </div>
          </div>
          <div class="card-body d-flex justify-content-center align-items-center">
            <%= form_with(url: filter_students_path, method: "get", id: "course-filter-form") do |form| %>
              <label for="course_id">Select Course</label>
              <div class="form-group d-flex align-items-center">
                  <%= render 'shared/course_selector' %>
              </div>
                <%= form.submit "Filter", class: "btn btn-primary mb-3" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <%= form_with(url: delete_students_path, method: "post", id: "manage-students-form") do |form| %>
      <table class="table table-bordered">
        <thead class="thead-light">
          <tr>
            <th>Email</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>UIN</th>
            <th>Course</th>
            <th>Gender</th>
            <th>Nationality</th>
            <th>Ethnicities</th>
            <th>Work Authorization</th>
            <th>Willingness to Sign Contracts</th>
            <th>Delete?</th>
          </tr>
        </thead>
        <tbody>
          <% if @students.present? %>
            <% @students.each do |user| %>
              <% student = user.student %>
              <tr>
                <td><%= user.email %></td>
                <td><%= user.first_name %></td>
                <td><%= user.last_name %></td>
                <td><%= student.uin%></td>
                <td><%= "CSCE " + student.course.course_number.to_s + "-" + student.course.section.to_s + "-" + student.course.semester %></td>
                <td><%= student.gender %></td>
                <td><%= student.nationality %></td>
                <td>
                  <% if @ethnicity_names_by_student[user.user_id].present? %>
                    <ul>
                      <% @ethnicity_names_by_student[user.user_id].each do |ethnicity_name| %>
                        <li><%= ethnicity_name %></li>
                      <% end %>
                    </ul>
                  <% else %>
                    No ethnicity information available
                  <% end %>
                </td>
                <td><%= student.work_auth %></td>
                <td><%= student.contract_sign %></td>
                <td>
                  <%= form.check_box "delete_students_emails[]", { value: user.email }, user.email, nil %>
                </td>
              </tr>
            <% end %>
          <% end %>      
        </tbody>
      </table>
      <div class="d-flex justify-content-center align-items-center">
      <%= form.button "Delete Students", class: "btn btn-danger m-2", id: "save-button", onclick: "return confirm('Are you sure you want to delete the selected students?');" do %>
        <i class="fas fa-trash-alt"></i> Delete Students
      <% end %>
      </div>
    <% end %>
  </div  
</body>