config/routes.rb
Rails.application.routes.draw do
	get 'sponsor_restrictions/edit'
	get 'sponsor_restrictions/new'
	root 'home#index'

	get '/auth/google_oauth2', as: 'google_login'
	get '/auth/google_oauth2/callback', to: 'sessions#google_auth'
	get '/logout', to: 'sessions#destroy'

	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
	get "profregistration", to: "profregistration#index"
	post "profregistration", to: "profregistration#create"

	get "addProjects", to: "projects#new"
	post "addProjects", to: "projects#create"

	get "/profLanding", to: "prof_landing#index"

	get "studentform", to:"studentform#index"
	post "studentform", to: "studentform#create"

	get "adminlanding", to: "adminlanding#index"

	get "manageprof", to: "manageprof#index"
	post '/manageprof/save_change', to: 'manageprof#save_change', as: 'save_change'
	post '/manageprof/add_professor', to: 'manageprof#add_professor', as: 'add_professor'

  get "configuration", to: "adminlanding#configuration"
  post "update_configuration", to: "adminlanding#update_configuration"
  
	get "open_close_student_form", to: "adminlanding#open_close_student_form"
	post "open_close_student_form", to: "adminlanding#update_open_close_student_form"

	get "managestudents", to: "managestudents#index"
	get "/managestudents/filter_students", to: "managestudents#filter_students", as: "filter_students"
	post '/managestudents/delete_students', to: 'managestudents#delete_students', as: 'delete_students'

	# Defines the root path route ("/")
	# root "articles#index"
	get '/devtest', to: 'dev_test#index'
	post '/devtest/upload_resume', to: 'dev_test#upload_resume'

	resources :sections, only: [:new, :create]

	get 'changeweights', to: 'changeweights#index'
	post 'changeweights/save_weights', to: 'changeweights#save_weights', as: 'save_weights'
	# get 'dev_test/classify', to: 'dev_test#classify'
	resources :projects do
		member do
			get "projects", to:"projects#index"
			delete "projects/:id", to:"projects#destroy"
		end
		resources :sponsor_restrictions
		resources :sponsor_preferences
	end


  resources :projects do
    member do
      get "projects", to:"projects#index"
      delete "projects/:id", to:"projects#destroy"
    end
  end

  get 'prof_projects_ranking', to: 'professor_preferences#index'
  post 'prof_projects_ranking', to: 'professor_preferences#save_rankings'

  post 'dump_database', to: 'database_dump#dump_database'

  get 'view_results', to: 'results#index', as: 'results'
  get 'results_export/:semester/:project.csv', to: 'results#export', as: 'results_export'

  get "manageCourses", to: "manage_courses#index"
  post "manageCourses/edit_courses", to: "manage_courses#edit_courses", as: "edit_courses"
	post "manageCourses/add_course", to: "manage_courses#add_course", as: "add_course"

	get "viewProfProjectPreferences", to: "view_prof_project_preferences#index"
	post '/update_professor_preferences', to: 'view_prof_project_preferences#update_professor_preferences', as: 'update_professor_preferences'
	resources :view_prof_project_preferences do
		post 'assign_professor', on: :collection
	end

end

app/models/project.rb
class Project < ApplicationRecord
  self.primary_key = 'project_id'

  belongs_to :course, foreign_key: 'course_id', primary_key: 'course_id', optional: true
  
  has_many :professor_preferences, foreign_key: 'project_id', primary_key: 'project_id'
  has_many :scores_entities, foreign_key: 'project_id', primary_key: 'project_id'
  has_many :sponsor_restrictions, foreign_key: 'project_id', primary_key: 'project_id', inverse_of: :project
  has_many :sponsor_preferences, foreign_key: 'project_id', primary_key: 'project_id', inverse_of: :project

  accepts_nested_attributes_for :sponsor_preferences, reject_if: lambda { |attributes| attributes['preference_type'].blank? }, allow_destroy: true
  accepts_nested_attributes_for :sponsor_restrictions, reject_if: lambda { |attributes| attributes['restriction_type'].blank? }, allow_destroy: true

  validates :name, presence: true
  validates :description, presence: true
  validates :sponsor, presence: true
  validates :semester, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # ToDo Check with team
  before_action :authorize_admin_or_prof, unless: -> { Rails.env.development? || Rails.env.test? }
  protect_from_forgery except: :destroy
  def index
    @role = nil

    if session[:user_id]
      user_id = session[:user_id]
      user = User.find(user_id)
      @role = user.role
    end

    @semesters = Project.pluck(:semester).uniq
    @selected_semester = params[:semester]

    @projects = if @selected_semester.present?
      Project.where(semester: @selected_semester)
    else
      Project.all
    end
  end

  def new
    @semesters = generate_semesters
    @project = Project.new
    @restrictions = {}
    @restriction_count = params[:restriction_count]
    @preference_count = params[:preference_count]
    render_to_string =render_to_string

    @restrictions['gender'] = STUDENT_STATUS_CONSTANTS['gender']
    @restrictions['work_auth'] = STUDENT_STATUS_CONSTANTS['work_auth']
    @restrictions['contract_sign'] = STUDENT_STATUS_CONSTANTS['contract_sign']
    @restrictions['nationality'] = STUDENT_STATUS_CONSTANTS['nationality']

    if @restriction_count.present?
      n = @restriction_count.to_i
      (1..n).each { |i|
        @project.sponsor_restrictions.build
      }
    end

    if @preference_count.present?
      n = @preference_count.to_i
      n.times {@project.sponsor_preferences.build}
    end
  end

  def append_sponsor
    len = @project.sponsor_restrictions.length
    @project.sponsor_restrictions.clear

    len = len + 1
    len.times {@project.sponsor_restrictions.build}
    @content = ''
    for i in 1..len do
      @content += render_to_string(partial: 'shared/sponsor_restrictions', locals: { f: @project.sponsor_restrictions[i], key: '' })
    end
    render plain:@content
  end

  def create
    @semesters = generate_semesters
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        flash[:notice] = "Project was successfully created"
        format.html { redirect_to "/projects", notice: "Project was successfully created" }
      else
        flash[:error] =  @project.errors.full_messages.join(', ')
        format.html { render :new, status: :unprocessable_entity}
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @semesters = generate_semesters
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project was successfully deleted"
    redirect_to projects_path
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project was successfully updated"
      redirect_to projects_path
    else
      render :edit, status: :unprocessable_entity
    end
  end


  private
    def project_params
      params.require(:project).permit(:name, :semester, :sponsor, :description, :info_url,
                                      sponsor_restrictions_attributes: [:restriction_type, :restriction_val, :_destroy],
                                      sponsor_preferences_attributes: [:preference_type, :preference_val, :bonus_amount, :_destroy])
    end

    def generate_semesters
      current_year = Time.now.year
      semesters = []

      (0..2).each do |year_offset|
        year = current_year + year_offset
        semesters << "Spring #{year}"
        semesters << "Summer #{year}"
        semesters << "Fall #{year}"
      end

      semesters
    end
end

app/views/projects/edit.html.erb
<!-- app/views/projects/edit.html.erb -->

<div class="container">
  <h1 class="text-center my-4">Edit Project</h1>

  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= render 'shared/notification' %>

      <%= form_for @project do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :sponsor %>
          <%= f.text_field :sponsor, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control', rows: 5 %>
        </div>

        <div class="form-group">
          <%= f.label :info_url %>
          <%= f.text_field :info_url, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :semester %>
          <%= f.select :semester, options_for_select(@semesters, @project.semester), {}, class: 'form-control' %>
        </div>
        <div class="form-actions text-center mb-4">
          <br/>
          <%= f.submit "Update", class: 'btn btn-primary' %>
          <%= link_to "Back", projects_path, class: 'btn btn-danger custom-maroon-button' %>
        </div>
      <% end %>

        <br>

        <!-- Sponsor Restrictions -->
          <div class="card mb-4" id="sponsor_restrictions_div">
            <div class="card-header custom-card-header">
              <div class="row">
                <div class="col text-left">
                  <h5 class="card-title">Sponsor Restriction</h5>
                </div>
                <div class="col">
                    <%= link_to new_project_sponsor_restriction_path(@project), class: "btn btn-success float-end", id: "Add_Sponsor_Restriction" do %>
                      <i id = "Add_Sponsor_Restriction" class="fas fa-plus text-right"></i>
                    <% end %>
                </div>
              </div>
            </div>
          <!-- app/views/sponsor_restrictions/_sponsor_restriction.html.erb -->
          <% @project.sponsor_restrictions.each do |sponsor_restriction| %>

            <div class="card-body">
              <p class="card-text">Type: <%= sponsor_restriction.restriction_type %></p>
              <p class="card-text">Value: <%= sponsor_restriction.restriction_val %></p>
              <div class="row">
                <div class="col text-right">
                  <%= link_to(edit_project_sponsor_restriction_path(@project, sponsor_restriction), class: 'btn btn-danger custom-maroon-button') do %>
                    <i class="fas fa-pencil-alt"></i> Edit
                  <% end %>
                </div>
                <div class = "col text-center">
                  <%= button_to project_sponsor_restriction_path(@project, sponsor_restriction), method: :delete, 'data-method' => 'delete', data: { confirm: "Are you sure you want to delete this sponsor restriction?" }, class: 'btn btn-danger', onclick: "return confirm('Are you sure you want to delete this sponsor restriction?')" do %>
                    <i class="fas fa-trash-alt"></i> Delete
                  <% end %>
                </div>
              </div>
              <hr/>
            </div>
            <% end %>
          </div>

        <!-- Sponsor Preferences -->
          <div class="card mb-4" id = "sponsor_preferences_div">
            <div class="card-header custom-card-header">
              <div class="row">
                <div class="col text-left">
                  <h5 class="card-title">Sponsor Preference</h5>
                </div>
                <div class="col text-right">
                  <%= link_to new_project_sponsor_preference_path(@project), class: "btn btn-success float-end", id: "Add_Sponsor_Preference" do %>
                    <i class="fas fa-plus text-right"></i>
                  <% end %>
                </div>
              </div>
            </div>
          <% @project.sponsor_preferences.each do |sponsor_preference|%>
              <div class="card-body">
                <p class="card-text">Type: <%= sponsor_preference.preference_type %></p>
                <p class="card-text">Value: <%= sponsor_preference.preference_val %></p>
                <p class="card-text">Bonus Amount: <%= sponsor_preference.bonus_amount %></p>
                <div class="row">
                  <div class="col text-right">
                    <%= link_to(edit_project_sponsor_preference_path(@project, sponsor_preference), class: 'btn btn-primary') do %>
                      <i class="fas fa-pencil-alt"></i> Edit
                    <% end %>
                  </div>

                  <div class = "col text-center">
                    <%= button_to project_sponsor_preference_path(@project, sponsor_preference), method: :delete, 'data-method' => 'delete', data: { confirm: "Are you sure you want to delete this sponsor preference?" }, class: 'btn btn-danger', onclick: "return confirm('Are you sure you want to delete this sponsor preference?')" do %>
                      <i class="fas fa-trash-alt"></i> Delete
                    <% end %>
                  </div>
                </div>
                <hr/>

              </div>
            <% end %>
          </div>

    </div>
  </div>
</div>

app/views/projects/index.html.erb
<%= render 'shared/generic_page_header' %>
<%= render 'shared/notification' %>
<body>
<div class="container">
  <h1 class="text-center my-4">Texas A&M University Projects</h1>

  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header custom-card-header">
          <div class="row">
            <div class="col">
              Filter by Semester
            </div>
            <div class="col float-end">
              <% if @role == 'admin' ||  Rails.env.test? %>
                <%= button_to "Add Project", addProjects_path, :method => :get , class: 'btn btn-success mb-2 float-end' %>
              <% end %>
            </div>
          </div>
        </div>

        <div class="card-body">
          <%= form_tag(projects_path, method: :get, class: 'form-inline') do %>
            <div class="form-group mb-2 mr-2">
              <%= select_tag :semester, options_for_select(@semesters, @selected_semester), include_blank: "All Semesters", class: 'form-control', id: 'Semester' %>
            </div>
            <%= submit_tag "Filter", class: 'btn btn-primary mb-2' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row justify-content-center mt-4">
    <div class="col-md-8">
      <% @projects.each do |project| %>
        <div class="card mb-4">
          <div class="card-header custom-card-header">
            <div class="row">
              <div class="col">
                <h5 class="card-title"><%= project.name %></h5>
              </div>
              <div class="col text-right">
              <% if @role == 'admin' ||  Rails.env.test? %>
                <%= link_to edit_project_path(project), class: "btn btn-danger custom-maroon-button" do %>
                  <i class="fas fa-edit"></i> Edit
                  <% end %>
              <% end %>
              </div>
              <div class="col text-right">
                <!-- Delete Link -->
                <div class="col">
                  <% if @role == 'admin' ||  Rails.env.test? %>
                    <%= button_to project_path(project), method: :delete, 'data-method' => 'delete', data: { confirm: "Are you sure you want to delete this project?" }, class: "btn btn-danger d-inline", onclick: "return confirm('Are you sure you want to delete this sponsor preference?')" do %>
                      <i class="fas fa-trash-alt"></i> Delete
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div id="description<%= project.id %>" >
            <div class="card-body">
              <h5 class="card-title"><%= project.sponsor %></h5>
              <p class="card-text"><%= project.description %></p>
              <% if project.info_url.present? %>
                <a href="<%= project.info_url %>" class="btn btn-primary">
                  <i class="fas fa-external-link-alt"></i> Link
                </a>

            <%end %>
              <% if project.sponsor_restrictions.present? %>
                <h5 class="mt-3">Sponsor Restrictions:</h5>
                <ul>
                  <% project.sponsor_restrictions.each do |restriction| %>
                    <li><%= restriction.restriction_type %>: <%= restriction.restriction_val %></li>
                  <% end %>
                </ul>
              <%end%>

              <!-- Display Sponsor Preferences -->
              <% if project.sponsor_preferences.present? %>
                <h5 class="mt-3">Sponsor Preferences:</h5>
                <ul>
                  <% project.sponsor_preferences.each do |preference| %>
                    <li><%= preference.preference_type %>: <%= preference.preference_val %> | <%= preference.bonus_amount %>  </li>
                  <% end %>
                </ul>
              <%end%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center mt-4 text-center">
    <hr />
    <% if @role == 'admin' ||  Rails.env.test?%>
      <%= button_to "Add Project", addProjects_path, :method => :get , class: 'btn btn-success mb-2' %>
    <% end %>
  </div>

</div>
</body>

app/views/projects/new.html.erb
<html>
<head>
  <!-- Add jQuery library if not already included -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


  <title>Professor Registration</title>
  <div class="container">
    <%= render 'shared/notification' %>
  </div>

  <style>
      /* Light Mode Styles */
  </style>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<div class="d-flex justify-content-between align-items-center">
      <%= link_to "Back to Projects Page", projects_path, class: "btn btn-danger custom-maroon-button m-3", id: "back-button" %>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h1 class="text-center mb-4">Project Registration</h1>

      <label>Number of Restrictions</label>
      <%= form_tag(addProjects_path, method: :get, class: 'form-inline') do %>
        <div class="form-group mb-2 mr-2">
          <%= hidden_field_tag :preference_count, @preference_count %>
          <input type="number" class="form-control rank-input"  min="0" max="100" name="restriction_count"
                 placeholder="Select number of restrictions and click Add Restrictions"
                 value="<%=@restriction_count %>">
        </div>
        <%= submit_tag "Add Restrictions", class: 'btn btn-primary mb-2', id: "Add_Sponsor_Preference" %>
      <% end %>

      <label>Number of Preferences</label>
      <%= form_tag(addProjects_path, method: :get, class: 'form-inline') do %>
        <div class="form-group mb-2 mr-2">
          <%= hidden_field_tag :restriction_count, @restriction_count %>
          <input type="number" class="form-control rank-input"  min="0" max="100" name="preference_count"
                 placeholder="Select number of preferences and click Add Preferences"
                 value="<%=@preference_count %>">
        </div>
        <%= submit_tag "Add Preferences", class: 'btn btn-primary mb-2' %>
      <% end %>

      <%= form_with(model: @project, url: "/addProjects", local: true) do |form| %>
        <div class="form-group mb-3">
          <%= form.label :name %><span class="text-danger">*</span>
          <%= form.text_field :name, placeholder: 'Enter name of the project', :class => "form-control", :required => true%>
        </div>
        <div class="form-group mb-3">
          <%= form.label :semester %><span class="text-danger">*</span>
          <%= form.select :semester, options_for_select(@semesters), prompt: 'Select a Semester', :class => "form-control", required: true %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :sponsor %><span class="text-danger">*</span>
          <%= form.text_field :sponsor, placeholder: 'Enter Name of the sponsor', :class => "form-control", :required => true%>
        </div>

        <div class="form-group mb-3">
          <%= form.label :description %><span class="text-danger">*</span>
          <%= form.text_area :description, placeholder: 'Give a brief description about the project', :class => "form-control", :required => true%>
        </div>

        <div class="form-group mb-3">
          <%= form.label :info_url %>
          <%= form.text_field :info_url , placeholder: 'Enter additional links' , :class => "form-control"%>
        </div>


        <!-- Sponsor Restrictions -->
        <div class="form-group row">
          <div class="row">
            <div class="col text-left">
              <h3 class="col-8">Sponsor Restrictions</h3>
            </div>
          </div>
        </div>


        <div class="field form-group mb-3" id="sponsorRestrictions">
            <%= form.fields_for :sponsor_restrictions do |restriction_fields| %>
            <%= render partial: 'shared/sponsor_restrictions', locals: { f: restriction_fields, key: ""} %>
            <% end %>
        </div>

        <!-- Sponsor Preferences -->
        <div class="form-group row">
          <div class="col text-left">
            <h3 class="col-8">Sponsor Preferences</h3>
          </div>
          <div class="col text-right">

          </div>
        </div>

        <div class="field form-group mb-3" id="sponsorPreferences">
            <%= form.fields_for :sponsor_preferences do |preference_fields| %>
              <%= render partial: 'shared/sponsor_preference', locals: {f: preference_fields, key:''} %>
            <% end %>
        </div>

        <div class="text-center mt-4">
          <%= form.submit 'Create Project', :class => "btn btn-success" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

<script>
    // JavaScript to toggle dark mode
    const darkModeToggle = document.getElementById('dark-mode-toggle');
    const htmlElement = document.documentElement;

    darkModeToggle.addEventListener('click', () => {
        htmlElement.classList.toggle('dark-mode');
    });

    // function addField(containerId, fieldId) {
    //     var container = document.getElementById(containerId);
    //     var field = document.getElementById(fieldId).cloneNode(true);
    //     const lastId = document.querySelector('#fieldsetContainer').lastElementChild.id;
    //
    //     const newId = parseInt(lastId, 10) + 1;
    //
    //     const newFieldset = document.querySelector('[id=”0"]').outerHTML.replace(/0/g,newId);
    //
    //     field.removeAttribute("id");
    //     container.appendChild(field);
    // const newFieldset = document.querySelector('[id=”0"]').outerHTML.replace(/0/g,newId);
    //
    // document.querySelector(“#fieldsetContainer”).insertAdjacentHTML(
    //     “beforeend”, newFieldset
    // );
    // }

    function addField(containerId)
    {
        var container = document.getElementById(containerId);
        const lastId = container.lastElementChild.id;
        const newId = parseInt(lastId, 10) + 1;
        console.log(newId, lastId)
        console.log(container.lastElementChild.innerHTML)
        var newElement = container.lastElementChild.outerHTML.replace(/0/g,newId)
        console.log(newElement)
        container.innerHTML += newElement;
    }

</script>
</body>
</html>

app/views/projects/new.js.erb
<% if @product.errors.any? %>
// JavaScript code to show a pop-up message
alert("<%= j @product.errors.full_messages.join(', ').html_safe %>");
<% end %>