config/routes.rb
Rails.application.routes.draw do
	get 'sponsor_restrictions/edit'
	get 'sponsor_restrictions/new'
	root 'home#index'

	get '/auth/google_oauth2', as: 'google_login'
	get '/auth/google_oauth2/callback', to: 'sessions#google_auth'
	get '/logout', to: 'sessions#destroy'

	# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
	get "profregistration", to: "profregistration#index"
	post "profregistration", to: "profregistration#create"

	get "addProjects", to: "projects#new"
	post "addProjects", to: "projects#create"

	get "/profLanding", to: "prof_landing#index"

	get "studentform", to:"studentform#index"
	post "studentform", to: "studentform#create"

	get "adminlanding", to: "adminlanding#index"

	get "manageprof", to: "manageprof#index"
	post '/manageprof/save_change', to: 'manageprof#save_change', as: 'save_change'
	post '/manageprof/add_professor', to: 'manageprof#add_professor', as: 'add_professor'

  get "configuration", to: "adminlanding#configuration"
  post "update_configuration", to: "adminlanding#update_configuration"
  
	get "open_close_student_form", to: "adminlanding#open_close_student_form"
	post "open_close_student_form", to: "adminlanding#update_open_close_student_form"

	get "managestudents", to: "managestudents#index"
	get "/managestudents/filter_students", to: "managestudents#filter_students", as: "filter_students"
	post '/managestudents/delete_students', to: 'managestudents#delete_students', as: 'delete_students'

	# Defines the root path route ("/")
	# root "articles#index"
	get '/devtest', to: 'dev_test#index'
	post '/devtest/upload_resume', to: 'dev_test#upload_resume'

	resources :sections, only: [:new, :create]

	get 'changeweights', to: 'changeweights#index'
	post 'changeweights/save_weights', to: 'changeweights#save_weights', as: 'save_weights'
	# get 'dev_test/classify', to: 'dev_test#classify'
	resources :projects do
		member do
			get "projects", to:"projects#index"
			delete "projects/:id", to:"projects#destroy"
		end
		resources :sponsor_restrictions
		resources :sponsor_preferences
	end


  resources :projects do
    member do
      get "projects", to:"projects#index"
      delete "projects/:id", to:"projects#destroy"
    end
  end

  get 'prof_projects_ranking', to: 'professor_preferences#index'
  post 'prof_projects_ranking', to: 'professor_preferences#save_rankings'

  post 'dump_database', to: 'database_dump#dump_database'

  get 'view_results', to: 'results#index', as: 'results'
  get 'results_export/:semester/:project.csv', to: 'results#export', as: 'results_export'

  get "manageCourses", to: "manage_courses#index"
  post "manageCourses/edit_courses", to: "manage_courses#edit_courses", as: "edit_courses"
	post "manageCourses/add_course", to: "manage_courses#add_course", as: "add_course"

	get "viewProfProjectPreferences", to: "view_prof_project_preferences#index"
	post '/update_professor_preferences', to: 'view_prof_project_preferences#update_professor_preferences', as: 'update_professor_preferences'
	resources :view_prof_project_preferences do
		post 'assign_professor', on: :collection
	end

end

app/controllers/adminlanding_controller.rb
class AdminlandingController < ApplicationController
    before_action :authorize_admin, unless: -> { Rails.env.development? || Rails.env.test? }
    def index
        if session[:user_id]
            @current_user = User.find_by(user_id: session[:user_id])
            @first_name = @current_user.first_name
            @last_name = @current_user.last_name
        end
    end

    def configuration
    end

    def update_configuration
        @config = Config.first_or_initialize
      
        # Convert semester dates to UTC
        params[:fall_semester_day] = params[:fall_semester_day].to_i
        params[:spring_semester_day] = params[:spring_semester_day].to_i
        params[:summer_semester_day] = params[:summer_semester_day].to_i

        params[:fall_semester_month] = params[:fall_semester_month].to_i
        params[:spring_semester_month] = params[:spring_semester_month].to_i
        params[:summer_semester_month] = params[:summer_semester_month].to_i

        if semester_order_valid? && @config.update(
            form_open: params[:form_open],
            form_close: params[:form_close],
            min_number: params[:min_number],
            max_number: params[:max_number],
            fall_semester_day: params[:fall_semester_day],
            fall_semester_month: params[:fall_semester_month],
            spring_semester_day: params[:spring_semester_day],
            spring_semester_month: params[:spring_semester_month],
            summer_semester_day: params[:summer_semester_day],
            summer_semester_month: params[:summer_semester_month]
          )
          flash[:notice] = "Changes made successfully"
        else
          flash[:error] = "Error updating the fields, ensure that dates are in the correct order and that all fields have values."
        end
      
        redirect_to configuration_path
      end
    
    private

    def semester_order_valid?
      year = Time.current.year
      spring_date = build_date(year, params[:spring_semester_month], params[:spring_semester_day])
      summer_date = build_date(year, params[:summer_semester_month], params[:summer_semester_day])
      fall_date = build_date(year, params[:fall_semester_month], params[:fall_semester_day])
    
      if spring_date && summer_date && fall_date && spring_date < summer_date && summer_date < fall_date
        return true
      else
        return false
      end
    end
    
    def build_date(year, month, day)
      Date.new(year, month.to_i, day.to_i) rescue nil
    end
end

app/views/adminlanding/configuration.html.erb
<script>
  $(document).ready(function () {
    // Function to update the days based on the selected month
    function updateDays(monthSelect, daySelect) {
      var selectedMonth = $(monthSelect).val();
      var daysInMonth = new Date(2023, selectedMonth, 0).getDate(); // Get the number of days in the selected month
      var currentSelectedDay = $(daySelect).val();

      // Update the days in the dropdown
      $(daySelect).empty();
      for (var i = 1; i <= daysInMonth; i++) {
        $(daySelect).append($('<option>', { value: i, text: i }));
      }

      // Restore the selected day if it's still valid for the new month
      if (currentSelectedDay <= daysInMonth) {
        $(daySelect).val(currentSelectedDay);
      }
    }

    // Event handlers for month dropdowns
    $('#spring_semester_month').change(function () {
      updateDays('#spring_semester_month', '#spring_semester_day');
    });

    $('#summer_semester_month').change(function () {
      updateDays('#summer_semester_month', '#summer_semester_day');
    });

    $('#fall_semester_month').change(function () {
      updateDays('#fall_semester_month', '#fall_semester_day');
    });

    // Initial update on page load
    updateDays('#spring_semester_month', '#spring_semester_day');
    updateDays('#summer_semester_month', '#summer_semester_day');
    updateDays('#fall_semester_month', '#fall_semester_day');
  });
</script>

<%= render 'shared/generic_page_header' %>
<%= render 'shared/notification' %>
<div class="d-flex justify-content-center align-items-center">
  <div>
    <div class="d-flex justify-content-center align-items-center">
      <h1>Configuration</h1>
    </div>

    

    <% config = Config.first %>
    <% if config.present? %>
      <p>Current Student Form Opening Date And Time: <%= config.form_open.in_time_zone("Central Time (US & Canada)").strftime("%H:%M %Y-%m-%d") %></p>
      <p>Current Student Form Closing Date And Time: <%= config.form_close.in_time_zone("Central Time (US & Canada)").strftime("%H:%M %Y-%m-%d") %></p>
    <% end %>

    <%= form_tag({controller: "adminlanding", action: "update_configuration"}, method: "post") do %>
      <div class="form-group">
        <%= label_tag(:form_open, "Form Open:") %>
        <%= datetime_local_field_tag(:form_open, nil, class: "form-control", required: true, value: (config.present? ? config.form_open.in_time_zone("Central Time (US & Canada)").strftime("%Y-%m-%dT%H:%M") : Time.current.in_time_zone("Central Time (US & Canada)").strftime("%Y-%m-%dT%H:%M"))) %>
      </div>

      <div class="form-group">
        <%= label_tag(:form_close, "Form Close:") %>
        <%= datetime_local_field_tag(:form_close, nil, class: "form-control", required: true, value: (config.present? ? config.form_close.in_time_zone("Central Time (US & Canada)").strftime("%Y-%m-%dT%H:%M") : Time.current.in_time_zone("Central Time (US & Canada)").strftime("%Y-%m-%dT%H:%M"))) %>
      </div>

      <hr>
      <p> Choose the minimum and maximum number of projects that you want students to be able to select.</p>
      <div class="form-group">
        <%= label_tag(:min_number, "Minimum Project Limit:") %>
        <%= number_field_tag(:min_number, nil, class: "form-control", required: true, value: config.present? ? config.min_number : 1, min: 1) %>
      </div>

      <div class="form-group">
        <%= label_tag(:max_number, "Maximum Project Limit:") %>
        <%= number_field_tag(:max_number, nil, class: "form-control", required: true, value: config.present? ? config.max_number : 10, min: 1) %>
      </div>

      <hr>
      <p> Choose the day and month that each semester starts.</p>
      <div class="form-group">
        <%= label_tag(:spring_semester_month, "Spring Semester Month:") %>
        <%= select_tag(:spring_semester_month, options_for_select(Date::MONTHNAMES[1..12].each_with_index.map { |month, index| [month, index + 1] }, config.present? ? config.spring_semester_month : nil), class: "form-control") %>
      </div>
      <div class="form-group">
        <%= label_tag(:spring_semester_day, "Spring Semester Day:") %>
        <%= select_tag(:spring_semester_day, options_for_select((1..31).to_a, config.present? ? config.spring_semester_day : nil), class: "form-control") %>
      </div>

      <br>

      <!-- Summer Semester -->
      <div class="form-group">
        <%= label_tag(:summer_semester_month, "Summer Semester Month:") %>
        <%= select_tag(:summer_semester_month, options_for_select(Date::MONTHNAMES[1..12].each_with_index.map { |month, index| [month, index + 1] }, config.present? ? config.summer_semester_month : nil), class: "form-control") %>
      </div>
      <div class="form-group">
        <%= label_tag(:summer_semester_day, "Summer Semester Day:") %>
        <%= select_tag(:summer_semester_day, options_for_select((1..31).to_a, config.present? ? config.summer_semester_day : nil), class: "form-control") %>
      </div>

      <br>

      <!-- Fall Semester -->
      <div class="form-group">
        <%= label_tag(:fall_semester_month, "Fall Semester Month:") %>
        <%= select_tag(:fall_semester_month, options_for_select(Date::MONTHNAMES[1..12].each_with_index.map { |month, index| [month, index + 1] }, config.present? ? config.fall_semester_month : nil), class: "form-control") %>
      </div>
      <div class="form-group">
        <%= label_tag(:fall_semester_day, "Fall Semester Day:") %>
        <%= select_tag(:fall_semester_day, options_for_select((1..31).to_a, config.present? ? config.fall_semester_day : nil), class: "form-control") %>
      </div>

      <hr>

      <div class="d-flex justify-content-center align-items-center">
        <%= submit_tag("Save", class: "btn btn-primary") %>
      </div>
    <% end %>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const formOpen = document.querySelector("#form_open");
    const formClose = document.querySelector("#form_close");

    formOpen.addEventListener("change", function() {
      if (formOpen.value >= formClose.value) {
        formOpen.setCustomValidity("Form open date must be before form close date.");
      } else {
        formOpen.setCustomValidity("");
      }
    });

    formClose.addEventListener("change", function() {
      if (formOpen.value >= formClose.value) {
        formOpen.setCustomValidity("Form open date must be before form close date.");
      } else {
        formOpen.setCustomValidity("");
      }
    });
  });
</script>

app/views/adminlanding/index.html.erb
<html>
<head>
  <title>Admin Landing Page</title>
</head>
<body>
  <%= render 'shared/notification' %>
  <div class="d-flex justify-content-between align-items-center">
    <%= link_to "Log Out", logout_path, method: :delete, class: "btn btn-primary m-3", id: "logout-button" %>
  </div>
  <div class="d-flex justify-content-center align-items-center flex-column">
    <div>
      <% if @current_user %>
        <h1>Welcome, <%= @first_name %> <%= @last_name %>!</h1>
      <% else %>
        <h1>Welcome, Admin!</h1>
      <% end %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "Manage Professors/Admins", manageprof_path, class: "btn btn-danger custom-maroon-button custom-button m-4", id: "button-1" %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "Manage Students", managestudents_path, class: "btn btn-danger custom-maroon-button custom-button mb-4", id: "button-1" %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "Manage Projects", projects_path, class: "btn btn-danger custom-maroon-button custom-button mb-4", id: "button-2" %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "View Match Results", results_path, class: "btn btn-danger custom-maroon-button custom-button mb-4", id: "button-3" %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "Manage Score Weights", changeweights_path, class: "btn btn-danger custom-maroon-button custom-button mb-4", id: "button-3" %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "Manage Courses", manageCourses_path, class: "btn btn-danger custom-maroon-button custom-button mb-4", id: "button-3" %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "Submit Project Preferences", prof_projects_ranking_path, class: "btn btn-danger custom-maroon-button custom-button mb-4", id: "button-3" %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "View Professor Project Preferences", viewProfProjectPreferences_path, class: "btn btn-danger custom-maroon-button custom-button mb-4", id: "button-3" %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= link_to "Configuration", configuration_path, class: "btn btn-danger custom-maroon-button custom-button mb-4", id: "button-3" %>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <%= button_to "Export Database", dump_database_path, method: :post, class: "btn btn-danger custom-maroon-button custom-button mb-4", id: "button-3" %>
    </div>
  </div>
</body>

app/views/adminlanding/open_close_student_form.html.erb
<div class="d-flex justify-content-between align-items-center">
  <%= link_to "Back to Admin Home Page", adminlanding_path, class: "btn btn-danger custom-maroon-button m-3", id: "back-button" %>
  <button class="btn btn-danger custom-maroon-button m-3" id="dark-mode-toggle">Toggle Dark Mode</button>
</div>

<div class="d-flex justify-content-center align-items-center">
  <div>
    <div class="d-flex justify-content-center align-items-center">
      <h1>Open and Close Student Form</h1>
    </div>

    <% if flash[:notice].present? %>
      <div class="alert alert-success alert-dismissible fade show m-4" role="alert">
        <%= flash[:notice] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <% if flash[:alert].present? %>
      <div class="alert alert-danger alert-dismissible fade show m-1" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <% config = Config.first %>
    <% if config.present? %>
      <p>Current Student Form Opening Date And Time: <%= config.form_open.in_time_zone("Central Time (US & Canada)").strftime("%H:%M %Y-%m-%d") %></p>
      <p>Current Student Form Closing Date And Time: <%= config.form_close.in_time_zone("Central Time (US & Canada)").strftime("%H:%M %Y-%m-%d") %></p>
    <% end %>

    <%= form_tag({controller: "adminlanding", action: "update_open_close_student_form"}, method: "post") do %>
      <div class="form-group">
        <%= label_tag(:form_open, "Form Open:") %>
        <%= datetime_local_field_tag(:form_open, nil, class: "form-control", required: true, value: Time.current.in_time_zone("Central Time (US & Canada)").strftime("%Y-%m-%dT%H:%M")) %>
      </div>

      <div class="form-group">
        <%= label_tag(:form_close, "Form Close:") %>
        <%= datetime_local_field_tag(:form_close, nil, class: "form-control", required: true, value: Time.current.in_time_zone("Central Time (US & Canada)").strftime("%Y-%m-%dT%H:%M")) %>
      </div>

      <br>
      <div class="d-flex justify-content-center align-items-center">
        <%= submit_tag("Save", class: "btn btn-primary") %>
      </div>
    <% end %>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const formOpen = document.querySelector("#form_open");
    const formClose = document.querySelector("#form_close");

    formOpen.addEventListener("change", function() {
      if (formOpen.value >= formClose.value) {
        formOpen.setCustomValidity("Form open date must be before form close date.");
      } else {
        formOpen.setCustomValidity("");
      }
    });

    formClose.addEventListener("change", function() {
      if (formOpen.value >= formClose.value) {
        formOpen.setCustomValidity("Form open date must be before form close date.");
      } else {
        formOpen.setCustomValidity("");
      }
    });
  });
</script>